---
- name: copy index html
  copy:
    src: index.html
    dest: /usr/share/nginx/html
    mode: '0644'
    owner: www-data
    group: root

- name: configuring nginx
  copy:
    src: default      
    dest: /etc/nginx/sites-available
    mode: '0644'
    owner: root
    group: root
  notify: restart nginx  
...
